wip

diff --git a/src/omnidb/install-omnidb b/src/omnidb/install-omnidb
--- a/src/omnidb/install-omnidb
+++ b/src/omnidb/install-omnidb
@@ -1,13 +1,28 @@
 #!/bin/bash
 cd "$(dirname "$0")"
 
+if [ "$1" == "" ]; then
+  echo "ERROR: version num parm required"
+  exit 1
+fi
+
+ver=$1
+svr=omnidb-server-$ver
+deb=$(echo ${svr}_linux_x86_64.deb)
+rpm=$(echo ${svr}_linux_x86_64.rpm)
+
+
 echo " "
-echo "## INSTALL OMNIDB v$1 ############################################"
+echo "## INSTALL OMNIDB v$ver ##########################################"
 source getPKMG.sh
 
 if [ "$PKMG" == "yum" ]; then
-  echo "not supported yet"
+  wget https://github.com/OmniDB/OmniDB/releases/download/$ver/$rpm
+  sudo rpm -ivh --force $rpm
 else
-  sudo apt install omnidb.deb
+  wget https://github.com/OmniDB/OmniDB/releases/download/$ver/$deb
+  sudo apt install -y $deb
 fi
 
+sudo systemctl start  omnidb
+sudo systemctl status omnidb
diff --git a/src/pgadmin/install-pgadmin b/src/pgadmin/install-pgadmin
--- a/src/pgadmin/install-pgadmin
+++ b/src/pgadmin/install-pgadmin
@@ -1,8 +1,16 @@
 #!/bin/bash
 cd "$(dirname "$0")"
 
+
+if [ "$1" == "" ]; then
+  echo "ERROR: version num parm required"
+  exit 1
+fi
+
+ver=$1
+
 echo " "
-echo "## INSTALL PGADMIN 4 v$1 #########################################"
+echo "## INSTALL PGADMIN 4 v$ver #######################################"
 source getPKMG.sh
 
 if [ "$PKMG" == "yum" ]; then
