tweak kfk & zook for ubu

diff --git a/src/kafka/install-kafka b/src/kafka/install-kafka
--- a/src/kafka/install-kafka
+++ b/src/kafka/install-kafka
@@ -1,11 +1,21 @@
 #!/bin/bash
 cd "$(dirname "$0")"
+
+if [ "$1" == "" ]; then
+  echo "ERROR: version num parm required"
+  exit 1
+fi
+
+echo " "
+echo "## INSTALL KAFKA v$1 ######################################"
+source getPKMG.sh
+
 set -x
 
 kafkaV=$1
 kafkaD=kafka_2.13-$kafkaV
 kafkaF=$kafkaD.tgz
-URL=http://mirror.cc.columbia.edu/pub/software/apache/kafka
+URL=https://mirrors.ocf.berkeley.edu/apache/kafka
 
 rm -rf $kafkaF
 wget $URL/$kafkaV/$kafkaF
@@ -18,4 +28,5 @@ sudo cp kafka.service     /etc/systemd/system/.
 rm -rf $kafkaF
 
 sudo systemctl daemon-reload
+sudo systemctl start kafka
 
diff --git a/src/zookeeper/install-zookeeper b/src/zookeeper/install-zookeeper
--- a/src/zookeeper/install-zookeeper
+++ b/src/zookeeper/install-zookeeper
@@ -1,6 +1,19 @@
 #!/bin/bash
 cd "$(dirname "$0")"
 
+if [ "$1" == "" ]; then
+  echo "ERROR: version num parm required"
+  exit 1
+fi
+
+echo " "
+echo "## INSTALL ZOOKEEPER v$1 ######################################"
+source getPKMG.sh
+
+set -x
+
+sudo apt-get install -y openjdk-11-jdk
+
 zookeeperV=$1
 
 id -u zk
@@ -8,12 +21,18 @@ rc=$?
 if [ "$rc" == "1" ]; then
   sudo useradd zk -m
 fi
-sudo usermod -a -G wheel zk
+
+if [ "$PKMG" == "yum" ]; then
+  sudo usermod -a -G wheel zk
+else
+  sudo usermod -a -G sudo zk
+fi
+
 sudo usermod --shell /bin/bash zk
 
 zookeeperD=apache-zookeeper-$zookeeperV-bin
 zookeeperF=$zookeeperD.tar.gz
-URL=http://mirror.cc.columbia.edu/pub/software/apache/zookeeper
+URL=https://mirrors.ocf.berkeley.edu/apache/zookeeper
 rm -rf $zookeeperF
 wget $URL/zookeeper-$zookeeperV/$zookeeperF
 tar xzf $zookeeperF
@@ -31,4 +50,6 @@ rm -f $zookeeperF
 sudo systemctl daemon-reload
 sudo mkdir -p /var/zookeeper
 sudo chown zk:zk -R /var/zookeeper
+
+sudo systemctl start zookeeper
 
