wip k8s

diff --git a/src/kubernetes/install-kubernetes b/src/kubernetes/install-kubernetes
--- a/src/kubernetes/install-kubernetes
+++ b/src/kubernetes/install-kubernetes
@@ -1,14 +1,24 @@
 
+channel="$1"
+if [ "$channel" == "" ]; then
+  echo "ERROR: You must specify k8s version"
+  exit 1
+fi
 
-echo "## Installing kubernetes (microk8s) ##"
+echo "## Installing kubernetes v$channel ##"
 
 set -x
 
-sudo snap install microk8s --classic
+sudo snap install microk8s --classic --channel=$channel/stable
+rc=$?
+if [ ! "$rc" == "0" ]; then
+  echo "ERROR: microk8s installation error"
+  exit $rc
+fi
 
 sudo systemctl enable iscsisd
 
-sudo microk8s enable dns dashboard helm3 openebs prometheus metrics-server
+sudo microk8s enable dns dashboard helm3 openebs prometheus metrics-server fluentd host-access
 
 sudo microk8s status --wait-ready
 
